---
title: "README"
author: "Gillian Sharer"
date: "July 3, 2016"
output: html_document
---

# Introduction to the AirPassengerPlots Shiny App
This shiny app is a tool to explore the month and year dependencies of the 
AirPassengers dataset in library(datasets). There are two tabs, the first of which
has two interactive plots controlled by the widgets in the sidebar. The second is 
a non-interactive display of the original dataset. 

In the first tab, the upper plot explores the dataset by year. Choose one or more 
years in the first selection box and it will plot months vs. number of air passengers 
for each selected year. There is a checkbox to also plot the average number of 
passengers for the year(s).

The lower plot explores the dataset by month. Choose one or more months in the
second selection box and it will plot years vs. number of air passengers for each
selected month. There is a checkbox to also plot the linear model fit for the 
month(s). You may need to scroll down the page to view the lower plot.

The second tab shows the dataset as a non-interactive plot of time vs. number of 
air passengers. Below the plot is a table display of the dataset. This tab will 
not display interactively; if you get no response from the widget input, make sure 
that you are in the first "Plot" tab.

To run this shiny app from RStudio:


\> runGitHub("AirlinePassengerPlots","gksharer")



